name: paper-registry-framework
version: '0.3'
main: net.Vivelle.paperRegistryFramework.PaperRegistryFramework
api-version: '1.21'
authors: [ Vivelle, DrDeffGoodwin ]
description: Nerdology teams very own vfx mod based around lodestone, datapack support included! :3
